<?xml version="1.0" encoding="utf-8"?>
<Project Sdk="Dalamud.NET.Sdk/14.0.1">
    <PropertyGroup>
        <Authors>nopjmp, Jessidhia, PGGB</Authors>
        <Version>3.0.0</Version>
        <Description>An FF14-Plugin that stops controller input from freezing on device changes</Description>
        <PackageProjectUrl>https://github.com/Jessidhia/DeviceChangeFix</PackageProjectUrl>
        <PackageLicenseExpression></PackageLicenseExpression>
        <IsPackable>false</IsPackable>
        <TargetFramework>net10.0-windows</TargetFramework>
    </PropertyGroup>

    <ItemGroup>
        <Content Include="global.json" />
        <Content Include="icon.png">
            <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
            <Visible>false</Visible>
        </Content>
    </ItemGroup>
</Project>